apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: loki
          image: grafana/loki:2.9.1
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: data
              mountPath: /data
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: false
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: data
          persistentVolumeClaim:
            claimName: loki-pvc
